all: run

beforeBuild: clean
	./scripts/before_build.sh

build: beforeBuild
	./scripts/build.sh

afterBuild: build
	./scripts/after_build.sh

run: afterBuild
	./scripts/run.sh

clean:
	./scripts/clean.sh

setup:
	./scripts/setup.sh && just run

listen:
	watchexec --exts js,css,html,rs,elm -i "target/**" -d 10000 -r -c -p -N -w ./ just run